### PR TITLE
fixes #554 weird hang/crash & race against nn_term

### LINKED ISSUE #554: weird hang/crash & race against nn_term
I think there is a problem with the req/rep state machines racing with nn_term.

https://ci.appveyor.com/project/gdamore/nanomsg/build/1.0.193/job/haswhuvgk3tv2lgr

I can't explain this crash, or hang, any other way; something doesn't add quite up.  The problem is seriously complicated to debug, due to the gazillion state machines involved. 

Interestingly enough, increasing the timeout for the connection request, which allows the TCP connections to be established properly, seems to clear this problem up.  (Its also relevant that this problem only was seen on Windows, which seems to require quite a bit longer for TCP to establish.)

### PR DESCRIPTION
**Pull request by gdamore**
I *hope* this will solve the hangs and crashes against nn_term.  I've done a few things.

nn_recvmsg and nn_sendmsg check explicitly for the nn_term case on error paths (fixes up error returns from some EBADFD cases.)

nn_term() actually *closes* the sockets on exit -- this arranges for all their resources to reaped.  Before we leaked like a sieve.  And, worse, we didn't always shut things down, and we didn't wait at all for threads to shut down.  As a consequence of this, nn_term() may take longer than it did before.  This shouldn't matter because nn_term() ought *never* be on your hot code path, or you're doing something badly wrong.

To make this work, I had to create a custom version of nn_close() that proceeds even in the face of the zombification.  This is used internally by nn_term.  Also the nn_global_hold_socket_locked() got a new argument.

nn_device had some bugs here, and the use of of the poll fds to loop was pretty bad, and the code was non-portable.  Its been replaced with a simpler design using two threads, one in each direction.  In addition to much easier to read and validate code, there should be scalability improvements, and the code should actually run quite a lot faster as we have half as many system calls to execute for each message.

This is totally untested at this point -- I'm hoping to get some CI test coverage with this PR.

### CODE REVIEW

File: src/core/global.c [hunk 1]
```diff
@@ -303,20 +307,28 @@ static void nn_global_term (void)
...
+            }
     }
 
     nn_glock_unlock ();
+
+    /* Make sure we really close resources, this will cause global
+       resources to be freed too when the last socket is closed. */
+    for (i = 0; i < NN_MAX_SOCKETS; i++) {
+        (void) nn_close_impl (i, 1);
+    }
```
Comment (JackDunaway) [inline src/core/global.c]: In this loop, each iteration obtains/releases the glock. Is this semantic correct, compared to holding the glock for the entirety of looping through all sockets?

Comment (JackDunaway) [inline src/core/global.c]: That is, compared to the strategy just above this line, where the glock is held around the loop that zombifies all sockets.

Comment (JackDunaway) [inline src/core/global.c]: PS -- I understand that if the glock needs to be held around the loop, then `nn_close_impl` would need to be refactored (to not glock), which would cascade these same considerations anywhere `nn_close_impl` is called.

File: tests/device.c [hunk 2]
```diff
@@ -51,7 +51,7 @@ void device1 (NN_UNUSED void *arg)
 
     /*  Run the device. */
     rc = nn_device (deva, devb);
-    nn_assert (rc < 0 && (nn_errno () == ETERM || nn_errno () == EBADF));
+    nn_assert (rc < 0 && (nn_errno () == ETERM));
```
Comment (JackDunaway) [inline tests/device.c]: Good to see the test tighten up here! If the previous pass criteria would switch between the two error codes, yet now it's just one, that seems like a step in a good direction!

File: src/core/global.c (hunk 1 above)
Comment (gdamore) [inline src/core/global.c]: Yes this is the right way. We're shutting down so the grab and release is fine here.
